spring:
  application:
    name: configmanagement
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

build:
  id: 1212
  version: 1.2.1.2
  name: "Default-Application-Build"
  type: "Application Build"

#build:
#  id: ${ID}
#  version: ${VERSION}
#  name: "Default-Build"

#  BUILD_ID=62830824;BUILD_NAME=sitamahalakshmi
#ID=4444;VERSION=1:1:1:1
management:
  endpoints:
    web:
      exposure:
        include: refresh
