spring:
  application:
    name: config-management
#  profiles:
#    active: dev

build:
  id: ${ID}
  version: ${VERSION}
  name: "Default-Build"

#  BUILD_ID=62830824;BUILD_NAME=sitamahalakshmi
#ID=4444;VERSION=1:1:1:1
